@Recipes_HostAddress = http://localhost:5275

GET {{Recipes_HostAddress}}/recipes/
Accept: application/json

###

GET {{Recipes_HostAddress}}/recipes/pizza
Accept: application/json

###

GET {{Recipes_HostAddress}}/recipes/chai
Accept: application/json

###
